package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "candidate", catalog = "nthrms")
public class Candidate implements java.io.Serializable {

    private Integer id;
    private String firstName;
    private String lastName;
    private String password;
    private String phone;
    private String email;
    private String address;
    private String link;
    private String status;
    private String description;
    private Date createDate;
    private Date lastUpdate;
    private Set<Phasedetail> phasedetails = new HashSet<Phasedetail>(0);
    private Set<History> histories = new HashSet<History>(0);
    private Set<Candidateskill> candidateskills = new HashSet<Candidateskill>(0);
    private Set<Experience> experiences = new HashSet<Experience>(0);
    private Set<Certificate> certificates = new HashSet<Certificate>(0);

    public Candidate() {
    }

    public Candidate(String firstName, String lastName, String password,
	    String phone, String email, String address, String link,
	    String status, String description, Date createDate,
	    Date lastUpdate, Set<Phasedetail> phasedetails,
	    Set<History> histories, Set<Candidateskill> candidateskills,
	    Set<Experience> experiences, Set<Certificate> certificates) {
	this.firstName = firstName;
	this.lastName = lastName;
	this.password = password;
	this.phone = phone;
	this.email = email;
	this.address = address;
	this.link = link;
	this.status = status;
	this.description = description;
	this.createDate = createDate;
	this.lastUpdate = lastUpdate;
	this.phasedetails = phasedetails;
	this.histories = histories;
	this.candidateskills = candidateskills;
	this.experiences = experiences;
	this.certificates = certificates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "FirstName", length = 100)
    public String getFirstName() {
	return this.firstName;
    }

    public void setFirstName(String firstName) {
	this.firstName = firstName;
    }

    @Column(name = "LastName", length = 100)
    public String getLastName() {
	return this.lastName;
    }

    public void setLastName(String lastName) {
	this.lastName = lastName;
    }

    @Column(name = "Password", length = 100)
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @Column(name = "Phone", length = 100)
    public String getPhone() {
	return this.phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    @Column(name = "Email", length = 100)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "Address", length = 1000)
    public String getAddress() {
	return this.address;
    }

    public void setAddress(String address) {
	this.address = address;
    }

    @Column(name = "Link", length = 100)
    public String getLink() {
	return this.link;
    }

    public void setLink(String link) {
	this.link = link;
    }

    @Column(name = "Status", length = 45)
    public String getStatus() {
	return this.status;
    }

    public void setStatus(String status) {
	this.status = status;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreateDate", length = 19)
    public Date getCreateDate() {
	return this.createDate;
    }

    public void setCreateDate(Date createDate) {
	this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LastUpdate", length = 19)
    public Date getLastUpdate() {
	return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
	this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
    public Set<Phasedetail> getPhasedetails() {
	return this.phasedetails;
    }

    public void setPhasedetails(Set<Phasedetail> phasedetails) {
	this.phasedetails = phasedetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
    public Set<History> getHistories() {
	return this.histories;
    }

    public void setHistories(Set<History> histories) {
	this.histories = histories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
    public Set<Candidateskill> getCandidateskills() {
	return this.candidateskills;
    }

    public void setCandidateskills(Set<Candidateskill> candidateskills) {
	this.candidateskills = candidateskills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
    public Set<Experience> getExperiences() {
	return this.experiences;
    }

    public void setExperiences(Set<Experience> experiences) {
	this.experiences = experiences;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
    public Set<Certificate> getCertificates() {
	return this.certificates;
    }

    public void setCertificates(Set<Certificate> certificates) {
	this.certificates = certificates;
    }

}
