package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Certificate generated by hbm2java
 */
@Entity
@Table(name = "certificate", catalog = "nthrms")
public class Certificate implements java.io.Serializable {

    private Integer id;
    private Candidate candidate;
    private String name;
    private String school;
    private String score;
    private Date startDate;
    private Date endDate;

    public Certificate() {
    }

    public Certificate(Candidate candidate) {
	this.candidate = candidate;
    }

    public Certificate(Candidate candidate, String name, String school,
	    String score, Date startDate, Date endDate) {
	this.candidate = candidate;
	this.name = name;
	this.school = school;
	this.score = score;
	this.startDate = startDate;
	this.endDate = endDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CandidateID", nullable = false)
    public Candidate getCandidate() {
	return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
	this.candidate = candidate;
    }

    @Column(name = "Name", length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "School", length = 100)
    public String getSchool() {
	return this.school;
    }

    public void setSchool(String school) {
	this.school = school;
    }

    @Column(name = "Score", length = 100)
    public String getScore() {
	return this.score;
    }

    public void setScore(String score) {
	this.score = score;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "StartDate", length = 10)
    public Date getStartDate() {
	return this.startDate;
    }

    public void setStartDate(Date startDate) {
	this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "EndDate", length = 10)
    public Date getEndDate() {
	return this.endDate;
    }

    public void setEndDate(Date endDate) {
	this.endDate = endDate;
    }

}
