package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phasedetail generated by hbm2java
 */
@Entity
@Table(name = "phasedetail", catalog = "nthrms")
public class Phasedetail implements java.io.Serializable {

    private Integer id;
    private Candidate candidate;
    private Phase phase;

    public Phasedetail() {
    }

    public Phasedetail(Candidate candidate, Phase phase) {
	this.candidate = candidate;
	this.phase = phase;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CandidateID", nullable = false)
    public Candidate getCandidate() {
	return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
	this.candidate = candidate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PhaseID", nullable = false)
    public Phase getPhase() {
	return this.phase;
    }

    public void setPhase(Phase phase) {
	this.phase = phase;
    }

}
