package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "nthrms")
public class Position implements java.io.Serializable {

    private Integer id;
    private String name;
    private String yearOfExperience;
    private String division;
    private String status;
    private String description;
    private Date createDate;
    private Date lastUpdate;
    private Set<Positionskill> positionskills = new HashSet<Positionskill>(0);
    private Set<User> users = new HashSet<User>(0);
    private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);

    public Position() {
    }

    public Position(String name, String yearOfExperience, String division,
	    String status, String description, Date createDate,
	    Date lastUpdate, Set<Positionskill> positionskills,
	    Set<User> users, Set<Vacancy> vacancies) {
	this.name = name;
	this.yearOfExperience = yearOfExperience;
	this.division = division;
	this.status = status;
	this.description = description;
	this.createDate = createDate;
	this.lastUpdate = lastUpdate;
	this.positionskills = positionskills;
	this.users = users;
	this.vacancies = vacancies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "Name", length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "YearOfExperience", length = 100)
    public String getYearOfExperience() {
	return this.yearOfExperience;
    }

    public void setYearOfExperience(String yearOfExperience) {
	this.yearOfExperience = yearOfExperience;
    }

    @Column(name = "Division", length = 100)
    public String getDivision() {
	return this.division;
    }

    public void setDivision(String division) {
	this.division = division;
    }

    @Column(name = "Status", length = 100)
    public String getStatus() {
	return this.status;
    }

    public void setStatus(String status) {
	this.status = status;
    }

    @Column(name = "Description", length = 1000)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreateDate", length = 19)
    public Date getCreateDate() {
	return this.createDate;
    }

    public void setCreateDate(Date createDate) {
	this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LastUpdate", length = 19)
    public Date getLastUpdate() {
	return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
	this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<Positionskill> getPositionskills() {
	return this.positionskills;
    }

    public void setPositionskills(Set<Positionskill> positionskills) {
	this.positionskills = positionskills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<User> getUsers() {
	return this.users;
    }

    public void setUsers(Set<User> users) {
	this.users = users;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
    public Set<Vacancy> getVacancies() {
	return this.vacancies;
    }

    public void setVacancies(Set<Vacancy> vacancies) {
	this.vacancies = vacancies;
    }

}
