package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Positionskill generated by hbm2java
 */
@Entity
@Table(name = "positionskill", catalog = "nthrms")
public class Positionskill implements java.io.Serializable {

    private Integer id;
    private Skill skill;
    private Position position;
    private Integer level;

    public Positionskill() {
    }

    public Positionskill(Skill skill, Position position) {
	this.skill = skill;
	this.position = position;
    }

    public Positionskill(Skill skill, Position position, Integer level) {
	this.skill = skill;
	this.position = position;
	this.level = level;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SkillID", nullable = false)
    public Skill getSkill() {
	return this.skill;
    }

    public void setSkill(Skill skill) {
	this.skill = skill;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PositionID", nullable = false)
    public Position getPosition() {
	return this.position;
    }

    public void setPosition(Position position) {
	this.position = position;
    }

    @Column(name = "Level")
    public Integer getLevel() {
	return this.level;
    }

    public void setLevel(Integer level) {
	this.level = level;
    }

}
