package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name = "skill", catalog = "nthrms")
public class Skill implements java.io.Serializable {

    private Integer id;
    private String name;
    private String type;
    private Set<Positionskill> positionskills = new HashSet<Positionskill>(0);
    private Set<Candidateskill> candidateskills = new HashSet<Candidateskill>(0);

    public Skill() {
    }

    public Skill(String name, String type, Set<Positionskill> positionskills,
	    Set<Candidateskill> candidateskills) {
	this.name = name;
	this.type = type;
	this.positionskills = positionskills;
	this.candidateskills = candidateskills;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "Name", length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "Type", length = 100)
    public String getType() {
	return this.type;
    }

    public void setType(String type) {
	this.type = type;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
    public Set<Positionskill> getPositionskills() {
	return this.positionskills;
    }

    public void setPositionskills(Set<Positionskill> positionskills) {
	this.positionskills = positionskills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "skill")
    public Set<Candidateskill> getCandidateskills() {
	return this.candidateskills;
    }

    public void setCandidateskills(Set<Candidateskill> candidateskills) {
	this.candidateskills = candidateskills;
    }

}
