package com.nthrms.pojo;

// Generated Jul 1, 2014 1:34:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "nthrms")
public class User implements java.io.Serializable {

    private Integer id;
    private Position position;
    private String username;
    private String password;
    private String phone;
    private String email;
    private Integer active;
    private String role;
    private Date createDate;
    private Date lastUpdate;
    private Set<History> histories = new HashSet<History>(0);

    public User() {
    }

    public User(Position position, String username, String password,
	    String phone, String email, Integer active, String role,
	    Date createDate, Date lastUpdate, Set<History> histories) {
	this.position = position;
	this.username = username;
	this.password = password;
	this.phone = phone;
	this.email = email;
	this.active = active;
	this.role = role;
	this.createDate = createDate;
	this.lastUpdate = lastUpdate;
	this.histories = histories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PositionID")
    public Position getPosition() {
	return this.position;
    }

    public void setPosition(Position position) {
	this.position = position;
    }

    @Column(name = "Username", length = 100)
    public String getUsername() {
	return this.username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    @Column(name = "Password", length = 100)
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @Column(name = "Phone", length = 100)
    public String getPhone() {
	return this.phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    @Column(name = "Email", length = 100)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "Active")
    public Integer getActive() {
	return this.active;
    }

    public void setActive(Integer active) {
	this.active = active;
    }

    @Column(name = "Role", length = 100)
    public String getRole() {
	return this.role;
    }

    public void setRole(String role) {
	this.role = role;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CreateDate", length = 19)
    public Date getCreateDate() {
	return this.createDate;
    }

    public void setCreateDate(Date createDate) {
	this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LastUpdate", length = 19)
    public Date getLastUpdate() {
	return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
	this.lastUpdate = lastUpdate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<History> getHistories() {
	return this.histories;
    }

    public void setHistories(Set<History> histories) {
	this.histories = histories;
    }

}
